enum MainViewModelStateType {
  INIT,
  LOADING,
  PAYMENT_SUCCESS,
  ERROR,
  PAYMENT_POST_AUTH_REVIEW,
  PAYMENT_FAILED,
  PAYMENT_PARTIAL_AUTH_DECLINED,
  PAYMENT_PARTIAL_AUTH_DECLINE_FAILED,
  PAYMENT_CANCELLED,
  PAYMENT_PARTIALLY_AUTHORISED,
  AUTHORIZED,
  PAYMENT_PROCESSING,
}

enum PaymentType {
  SAMSUNG_PAY,
  CARD,
  SAVED_CARD,
}
